export type Envs = {
  FEATURE_TLDRAW_ENABLED: boolean;
  TLDRAW_ASSETS_ENABLED: boolean;
  TLDRAW_ASSETS_MAX_SIZE_BYTES: number;
  TLDRAW_ASSETS_ALLOWED_MIME_TYPES_LIST: string[];
  TLDRAW_WEBSOCKET_URL: string;
  NOT_AUTHENTICATED_REDIRECT_URL: string;
};
