name: Test code

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  node: 22
jobs:
  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.node }}
      - name: npm ci
        run: npm ci --prefer-offline --no-audit
      - name: npm run test
        run: npm run test
        env:
          NODE_OPTIONS: "--unhandled-rejections=warn"

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.node }}
      - name: npm ci
        run: npm ci --prefer-offline --no-audit
      - name: npm run lint
        run: npm run lint
